lynis

diff --git a/lynis b/lynis
--- a/lynis
+++ b/lynis
@@ -320,6 +320,11 @@ ${YELLOW}Note: ${WHITE}Cancelling the program can leave temporary files behind${
 "
         wait_for_keypress
 
+        if [ ${CRONJOB} -eq 1 ]; then
+            echo "Quitting, to prevent multiple cron jobs running at the same time"
+            exit 1 # Manually exit, no cleanups to prevent deleting an active PID file
+        fi
+
         # Deleting any stale PID files that might exist. Note: Display function does not work yet at this point
         if [ -f "${MYHOMEDIR}/lynis.pid" ]; then rm -f "${MYHOMEDIR}/lynis.pid"; fi
         if [ -f "./lynis.pid" ]; then rm -f "./lynis.pid"; fi
