Minimized ifs.

diff --git a/include/functions b/include/functions
--- a/include/functions
+++ b/include/functions
@@ -151,7 +151,7 @@
                 LogText "Skipping search, as /dev/null is being used"
             fi
           else
-            ReportException ${TEST_NO} "Error in function call to CheckItem"
+            ReportException "${TEST_NO}" "Error in function call to CheckItem"
          fi
       }
 
@@ -165,52 +165,59 @@
     {
         local RETVAL=2
 
-        if [ "$#" -lt "2" ]; then
-            ReportException "${TEST_NO}" "Error in function call to ${FUNCNAME}"
-        else
-            LogText "${FUNCNAME}: checking value for application ${APP}"
-            LogText "${FUNCNAME}: ${OPTION} is set to ${1}"
+        LogText "${FUNCNAME}: checking value for application ${APP}"
+        LogText "${FUNCNAME}: ${OPTION} is set to ${1}"
 
-
+        case $# in
+        2)
             LogText "${FUNCNAME}: check if ${1} is equal to ${2}"
-
             if [ "$1" = "$2" ]; then
-              LogText "${FUNCNAME}: ${1} is equal to ${2}"
-              RETVAL=0
+                LogText "${FUNCNAME}: ${1} is equal to ${2}"
+                RETVAL=0
             fi
+        ;;
 
-            if ! [ -z ${3+x} ]; then
-                LogText "${FUNCNAME}: ${1} is equal to ${3}"
-                if [ "$2" = "$3" ]; then
-                    LogText "${FUNCNAME}: ${OPTION} is equal to ${3}"
-                    RETVAL=1
-                fi
+        3)
+            LogText "${FUNCNAME}: ${1} is equal to ${3}"
+            if [ "$2" = "$3" ]; then
+                LogText "${FUNCNAME}: ${OPTION} is equal to ${3}"
+                RETVAL=1
             fi
-        fi
+        ;;
+
+        *)
+            ReportException "${TEST_NO}" "Error in function call to ${FUNCNAME}"
+        ;;
+        esac
+
         return ${RETVAL}
     }
 
     ################################################################################
     # Name        : TestCase_NE()
     # Description : Test case for checking if value is not equal to something
-    # Returns     : (0 - SUCCESS;  1 - FAIL)
+    # Returns     : (0 - SUCCESS;  2 - FAIL)
     ################################################################################
     TestCase_NE()
     {
-        local RETVAL=1
-        if [ "$#" -ne "2" ]; then
-            ReportException "${TEST_NO}" "Error in function call to ${FUNCNAME}"
-        else
-            LogText "${FUNCNAME}: checking value for application ${APP}"
-            LogText "${FUNCNAME}: ${OPTION} is set to ${1}"
+        local RETVAL=2
 
+        LogText "${FUNCNAME}: checking value for application ${APP}"
+        LogText "${FUNCNAME}: ${OPTION} is set to ${1}"
+
+        case $# in
+        2)
             if [ "$1" != "$2" ]; then
               LogText "${FUNCNAME}: ${1} is not equal to ${2}"
               RETVAL=0
             else
               LogText "${FUNCNAME}: ${1} is equal to ${2}"
             fi
-        fi
+            ;;
+        *)
+            ReportException "${TEST_NO}" "Error in function call to ${FUNCNAME}"
+            ;;
+        esac
 
         return ${RETVAL}
     }
@@ -223,20 +230,25 @@
     TestCase_GT()
     {
         local RETVAL=1
-        if [ "$#" -ne "2" ]; then
-            ReportException "${TEST_NO}" "Error in function call to ${FUNCNAME}"
-        else
-            LogText "${FUNCNAME}: checking value for application ${APP}"
-            LogText "${FUNCNAME}: ${OPTION} is set to ${1}"
 
+        LogText "${FUNCNAME}: checking value for application ${APP}"
+        LogText "${FUNCNAME}: ${OPTION} is set to ${1}"
+
+        case $# in
+        2)
             LogText "${FUNCNAME}: checking if ${1} is greater than ${2}"
+
             if [ "$1" > "$2" ]; then
-              LogText "${FUNCNAME}: ${1} is greater than ${2}"
-              RETVAL=0
+                LogText "${FUNCNAME}: ${1} is greater than ${2}"
+                RETVAL=0
             else
-              LogText "${FUNCNAME}: ${1} is not greater than ${2}"
+                LogText "${FUNCNAME}: ${1} is not greater than ${2}"
             fi
-        fi
+            ;;
+        *)
+            ReportException "${TEST_NO}" "Error in function call to ${FUNCNAME}"
+            ;;
+        esac
 
         return ${RETVAL}
     }
@@ -249,17 +261,22 @@
     TestCase_GE()
     {
         local RETVAL=1
-        if [ "$#" -ne "2" ]; then
-            ReportException "${TEST_NO}" "Error in function call to ${FUNCNAME}"
-        else
-            LogText "${FUNCNAME}: checking value for application ${APP}"
-            LogText "${FUNCNAME}: ${OPTION} is set to ${1}"
 
+        LogText "${FUNCNAME}: checking value for application ${APP}"
+        LogText "${FUNCNAME}: ${OPTION} is set to ${1}"
+
+        case $# in
+        2)
             LogText "${FUNCNAME}: checking if ${1} is greater or equal ${2}"
-            if [ TestCase_EQ "${1}" "${2}"  ] || [ TestCase_GT "${1}" "${2}" ]; then
-              RETVAL=0
+            if TestCase_EQ "${1}" "${2}" || TestCase_GT "${1}" "${2}"; then
+                RETVAL=0
             fi
-        fi
+            ;;
+        *)
+            ReportException "${TEST_NO}" "Error in function call to ${FUNCNAME}"
+            ;;
+        esac
+
         return ${RETVAL}
     }
     ################################################################################
@@ -270,18 +287,23 @@
     TestCase_LT()
     {
         local RETVAL=1
-        if [ "$#" -ne "2" ]; then
-            ReportException "${TEST_NO}" "Error in function call to TestCase_GE"
-        else
+
+        case $# in
+        2)
             LogText "${FUNCNAME}: checking value for application ${APP}"
             LogText "${FUNCNAME}: ${OPTION} is set to ${1}"
 
             LogText "${FUNCNAME}: checking if ${1} is less than ${2}"
-            if ! [ TestCase_GE "${1}" "${2}"  ]; then
-              LogText "${FUNCNAME}:  ${1} is less than ${2}"
-              RETVAL=0
+            if ! TestCase_GE "${1}" "${2}"; then
+                LogText "${FUNCNAME}:  ${1} is less than ${2}"
+                RETVAL=0
             fi
-        fi
+            ;;
+        *)
+            ReportException "${TEST_NO}" "Error in function call to ${FUNCNAME}"
+            ;;
+        esac
+
         return ${RETVAL}
     }
 
@@ -293,18 +315,23 @@
     TestCase_LE()
     {
         local RETVAL=1
-        if [ "$#" -ne "2" ]; then
-            ReportException "${TEST_NO}" "Error in function call to ${FUNCNAME}"
-        else
+
+        case $# in
+        2)
             LogText "${FUNCNAME}: checking value for application ${APP}"
             LogText "${FUNCNAME}: ${OPTION} is set to ${1}"
 
             LogText "${FUNCNAME}: checking if ${1} is less or equal ${2}"
-            if [ TestCase_EQ "${1}" "${2}" ] || [ TestCase_LT "${1}" "${2}" ]; then
+            if TestCase_EQ "${1}" "${2}" || TestCase_LT "${1}" "${2}"; then
               LogText "${FUNCNAME}:  ${1} is less than ${2}"
               RETVAL=0
             fi
-        fi
+            ;;
+        *)
+            ReportException "${TEST_NO}" "Error in function call to ${FUNCNAME}"
+            ;;
+        esac
+
         return ${RETVAL}
     }
 
