Implemented less-than test case.

diff --git a/include/functions b/include/functions
--- a/include/functions
+++ b/include/functions
@@ -73,6 +73,7 @@
 #    TestCase_ValueNotEqual     Test case for checking if value is not equal to something
 #    TestCase_GreaterThan       Test case for checking if value is greater than something
 #    TestCase_GreaterOrEqual    Test case for checking if value is greater or equal something
+#    TestCase_LessThan          Test case for checking if value is less than something
 #
 #################################################################################
 
@@ -244,6 +245,23 @@
             ReportException "${TEST_NO}" "Error in function call to TestCase_GreaterOrEqual"
         else
             if [ TestCase_ValueEqual "${1}" "${2}"  ] || [ TestCase_GreaterThan "${1}" "${2}" ]; then
+              RETVAL=0
+            fi
+        fi
+        return ${RETVAL}
+    }
+    ################################################################################
+    # Name        : TestCase_LessThan()
+    # Description : Test case for checking if value is greater than something
+    # Returns     : (0 - SUCCESS;  1 - FAIL)
+    ################################################################################
+    TestCase_LessThan()
+    {
+        local RETVAL=1
+        if [ "$#" -ne "2" ]; then
+            ReportException "${TEST_NO}" "Error in function call to TestCase_GreaterOrEqual"
+        else
+            if ! [ TestCase_GreaterOrEqual "${1}" "${2}"  ]; then
               RETVAL=0
             fi
         fi
