Added --bin-dirs option

diff --git a/include/parameters b/include/parameters
--- a/include/parameters
+++ b/include/parameters
@@ -155,6 +155,24 @@
                 AUDITORNAME=$1
             ;;
 
+            # Binary directories (useful for incident response)
+            --bindirs | --bin-dirs)
+                if [ $# -gt 1 ]; then
+                    shift
+                    DIRS="$1"
+                    for DIR in $1; do
+                        if [ ! -d ${DIR} ]; then
+                            echo "Invalid bindir '${DIR}' provided (does not exist)"
+                            exit 1
+                        fi
+                    done
+                    BIN_PATHS="${DIRS}"
+                else
+                    echo "Need one or more directories (e.g. \"/mnt/cert/bin /mnt/cert/sbin\")"
+                    exit 1
+                fi
+            ;;
+
             # Perform tests (deprecated, use audit system)
             --check-all | --checkall | -c)
                 DisplayToolTip "Usage of option -c is deprecated. Please use: lynis audit system [options]"
