Added --rootdir for forensics

diff --git a/include/parameters b/include/parameters
--- a/include/parameters
+++ b/include/parameters
@@ -289,6 +289,22 @@
                 PURPLE="${NORMAL}";
             ;;
 
+            # Root directory (useful for forensics)
+            --rootdir | --root-dir)
+                if [ $# -gt 1 ]; then
+                    shift
+                    if [ -d $1 ]; then
+                        ROOTDIR="$1"
+                    else
+                        echo "Invalid rootdir provided (does not exist)"
+                        exit 1
+                    fi
+                else
+                    echo "Need a root directory (e.g. /mnt/forensics)"
+                    exit 1
+                fi
+            ;;
+
             # Skip execution of plugins
             --skip-plugins | --no-plugins)
                 SKIP_PLUGINS=1
