Added file check when a profile is provided

diff --git a/include/parameters b/include/parameters
--- a/include/parameters
+++ b/include/parameters
@@ -315,7 +315,11 @@
             --profile)
                 if [ $# -gt 1 ]; then
                     shift
-                    SEARCH_PROFILES=$1
+                    if [ ! -r "$1" ]; then
+                        echo "Fatal error: could not find or read the provided profile ($1)"
+                        exit 1
+                    fi
+                    SEARCH_PROFILES="$1"
                 else
                     echo "Specify the profile (lynis audit system --profile /home/michael/myprofile.prf)"
                     exit 1
