Improve DragonFly support (#329)
* Update facter location for BSDs

BSDs tend to place third party binaries in /usr/local rather than /usr

* Add support for DragonFly boot loader detection

DragonFly BSD has the same file paths for the bootloader as FreeBSD

* Add kernel module checking for DragonFly

DragonFly BSD checks kernel modules the same way as FreeBSD

* Add DragonFly check for login shells

DragonFly's login files are the same as FreeBSD's

* Add HAMMER PFS Detection

All PFS mounts in HAMMER systems for DragonFly will be detected now

diff --git a/include/tests_kernel b/include/tests_kernel
--- a/include/tests_kernel
+++ b/include/tests_kernel
@@ -314,6 +314,37 @@
 #
 #################################################################################
 #
+    # Test        : KRNL-5831
+    # Description : Checking DragonFly loaded kernel modules
+    Register --test-no KRNL-5831 --os DragonFly --weight L --network NO --category security --description "Checking DragonFly loaded kernel modules"
+    if [ ${SKIPTEST} -eq 0 ]; then
+        Display --indent 2 --text "- Checking active kernel modules"
+        LogText "Test: Active kernel modules (KLDs)"
+        LogText "Description: View all active kernel modules (including kernel)"
+        LogText "Test: Checking modules"
+        if [ -f /sbin/kldstat ]; then
+            FIND=`kldstat | ${GREPBINARY} -v 'Name' | ${TRBINARY} -s ' ' | ${CUTBINARY} -d ' ' -f6`
+            if [ $? -eq 0 ]; then
+                LogText "Loaded modules according kldstat:"
+                N=0
+                for I in ${FIND}; do
+                    LogText "Loaded module: ${I}"
+                    Report "loaded_kernel_module[]=${I}"
+                    N=$((N + 1))
+                done
+                Display --indent 4 --text "Found ${N} kernel modules" --result "${STATUS_DONE}" --color GREEN
+              else
+                Display --indent 4 --text "Test failed" --result "${STATUS_WARNING}" --color RED
+                LogText "Result: Problem with executing kldstat"
+            fi
+          else
+            echo "[ ${WHITE}SKIPPED${NORMAL} ]"
+            LogText "Result: no results, can't find /sbin/kldstat"
+        fi
+    fi
+#
+#################################################################################
+#
     # Test        : KRNL-5770
     # Description : Checking Solaris load modules
     Register --test-no KRNL-5770 --os Solaris --weight L --network NO --category security --description "Checking active kernel modules"
