Perform configuration integrity test for AIDE

diff --git a/include/tests_file_integrity b/include/tests_file_integrity
--- a/include/tests_file_integrity
+++ b/include/tests_file_integrity
@@ -72,7 +72,14 @@
         if [ "${AIDECONFIG}" = "" ]; then
             Display --indent 6 --text "- AIDE config file" --result "NOT FOUND" --color YELLOW
           else
-            Display --indent 6 --text "- AIDE config file" --result FOUND --color GREEN
+            logtext "Checking configuration file ${AIDECONFIG} for errors"
+            FIND=`${AIDEBINARY} --config=${AIDECONFIG} -D; echo $?`
+            if [ "${FIND}" = "0" ]; then
+                Display --indent 6 --text "- AIDE config file" --result FOUND --color GREEN
+              else
+                Display --indent 6 --text "- AIDE config file" --result WARNING --color YELLOW
+                ReportSuggestion "${TEST_NO}" "Check the AIDE configuratio file as it may contain errors"
+            fi
         fi
     fi
 #
